/**
 * Categorias da lista de ícones do readme.
 *
 * É a única fonte da divisão por grupos. `scripts/readme-table.mjs` valida que
 * a partição é total e exclusiva: todo ID de `icons/` aparece exatamente uma
 * vez. Ícone novo sem categoria quebra `npm run readme:check` em vez de sumir
 * no meio da tabela.
 *
 * A ordem daqui é a ordem das seções no readme.
 */
export const CATEGORIES = [
  {
    title: 'Marca `<gcruz.dev/>`',
    slug: 'marca',
    note: 'Os ícones da marca. Detalhes e assets em [Ícones da marca](#ícones-da-marca-gcruzdev).',
    ids: ['gcruz', 'gc'],
  },
  {
    title: 'Linguagens',
    slug: 'linguagens',
    ids: [
      'aiscript',
      'bash',
      'c',
      'clojure',
      'coffeescript',
      'cpp',
      'crystal',
      'cs',
      'dart',
      'elixir',
      'forth',
      'fortran',
      'gherkin',
      'golang',
      'haskell',
      'haxe',
      'java',
      'javascript',
      'julia',
      'kotlin',
      'latex',
      'lua',
      'markdown',
      'matlab',
      'nim',
      'ocaml',
      'octave',
      'perl',
      'php',
      'pkl',
      'powershell',
      'python',
      'r',
      'regex',
      'ruby',
      'rust',
      'scala',
      'solidity',
      'svg',
      'swift',
      'typescript',
      'v',
      'vala',
      'verilog',
      'webassembly',
      'zig',
    ],
  },
  {
    title: 'Marcação e estilo',
    slug: 'marcacao-e-estilo',
    ids: [
      'bootstrap',
      'css',
      'emotion',
      'html',
      'less',
      'materialui',
      'pug',
      'sass',
      'styledcomponents',
      'tailwindcss',
      'vuetify',
      'windicss',
    ],
  },
  {
    title: 'Front-end',
    slug: 'front-end',
    ids: [
      'alpinejs',
      'angular',
      'astro',
      'd3',
      'ember',
      'gatsby',
      'htmx',
      'jquery',
      'lit',
      'nextjs',
      'nuxtjs',
      'p5js',
      'pinia',
      'processing',
      'react',
      'reactivex',
      'reactrouter',
      'redux',
      'remix',
      'solidjs',
      'svelte',
      'threejs',
      'vuejs',
      'yew',
    ],
  },
  {
    title: 'Build e pacotes',
    slug: 'build-e-pacotes',
    ids: [
      'babel',
      'cmake',
      'gradle',
      'gulp',
      'maven',
      'npm',
      'pnpm',
      'rollupjs',
      'vite',
      'webpack',
      'yarn',
    ],
  },
  {
    title: 'Back-end e APIs',
    slug: 'back-end-e-apis',
    ids: [
      'actix',
      'adonis',
      'apollo',
      'appwrite',
      'bun',
      'deno',
      'django',
      'elysia',
      'expressjs',
      'fastapi',
      'firebase',
      'flask',
      'graphql',
      'jwt',
      'kafka',
      'ktor',
      'laravel',
      'nestjs',
      'nginx',
      'nodejs',
      'pydantic',
      'rabbitmq',
      'rails',
      'rocket',
      'spring',
      'supabase',
      'symfony',
      'dotnet',
      'uvicorn',
      'websocket',
      'workers',
    ],
  },
  {
    title: 'Banco de dados',
    slug: 'banco-de-dados',
    ids: [
      'cassandra',
      'dynamodb',
      'elasticsearch',
      'hibernate',
      'mongodb',
      'mysql',
      'oracle',
      'planetscale',
      'postgresql',
      'prisma',
      'redis',
      'sequelize',
      'sql',
      'sqlite',
    ],
  },
  {
    title: 'DevOps e infraestrutura',
    slug: 'devops-e-infraestrutura',
    ids: [
      'ansible',
      'bitbucket',
      'docker',
      'git',
      'github',
      'githubactions',
      'gitlab',
      'grafana',
      'ipfs',
      'jenkins',
      'kubernetes',
      'nix',
      'openshift',
      'openstack',
      'prometheus',
      'sentry',
      'terraform',
    ],
  },
  {
    title: 'Cloud e hospedagem',
    slug: 'cloud-e-hospedagem',
    ids: [
      'aws',
      'azure',
      'cloudflare',
      'gcp',
      'heroku',
      'netlify',
      'render',
      'replit',
      'vercel',
    ],
  },
  {
    title: 'Testes e qualidade',
    slug: 'testes-e-qualidade',
    ids: [
      'cypress',
      'eslint',
      'husky',
      'jest',
      'playwright',
      'postman',
      'prettier',
      'selenium',
      'testinglibrary',
      'vitest',
    ],
  },
  {
    title: 'Mobile e desktop',
    slug: 'mobile-e-desktop',
    ids: [
      'androidstudio',
      'capacitor',
      'electron',
      'flutter',
      'gtk',
      'qt',
      'tauri',
    ],
  },
  {
    title: 'IA e dados',
    slug: 'ia-e-dados',
    ids: ['anaconda', 'opencv', 'pytorch', 'ros', 'scikitlearn', 'tensorflow'],
  },
  {
    title: 'Jogos e 3D',
    slug: 'jogos-e-3d',
    ids: [
      'bevy',
      'blender',
      'gamemakerstudio',
      'godot',
      'haxeflixel',
      'robloxstudio',
      'unity',
      'unrealengine',
    ],
  },
  {
    title: 'Editores e IDEs',
    slug: 'editores-e-ides',
    ids: [
      'atom',
      'clion',
      'codepen',
      'eclipse',
      'emacs',
      'idea',
      'neovim',
      'phpstorm',
      'pycharm',
      'rider',
      'sublime',
      'vim',
      'visualstudio',
      'vscode',
      'vscodium',
      'webstorm',
    ],
  },
  {
    title: 'Hardware',
    slug: 'hardware',
    ids: ['arduino', 'raspberrypi'],
  },
  {
    title: 'Design e criação',
    slug: 'design-e-criacao',
    ids: [
      'ableton',
      'aftereffects',
      'audition',
      'autocad',
      'figma',
      'fontawesome',
      'illustrator',
      'photoshop',
      'premiere',
      'sketchup',
      'webflow',
      'wordpress',
      'xd',
    ],
  },
  {
    title: 'Sistemas operacionais',
    slug: 'sistemas-operacionais',
    ids: [
      'apple',
      'arch',
      'bsd',
      'debian',
      'kali',
      'linux',
      'mint',
      'plan9',
      'redhat',
      'ubuntu',
      'windows',
    ],
  },
  {
    title: 'Social e comunidades',
    slug: 'social-e-comunidades',
    ids: [
      'activitypub',
      'devto',
      'discord',
      'discordbots',
      'discordjs',
      'fediverse',
      'gmail',
      'instagram',
      'linkedin',
      'mastodon',
      'misskey',
      'spotify',
      'stackoverflow',
      'twitter',
    ],
  },
  {
    title: 'Produtividade e outros',
    slug: 'produtividade-e-outros',
    ids: ['azul', 'notion', 'obsidian'],
  },
];
